### ISSUE TITLE
git clone the repo or will make handle that?

### ISSUE THREAD

**Issue by SiddAjriY2Jaccount** [edouardpoitras/NowTrade#14]
Hello, 

Just to clarify, the NowTrade repo needs to be cloned to install it right? Or will makefile handle that? 

Thanks!

**Comment by edouardpoitras** [comment]
Hello.
Admittedly I haven't installed it in years, but I suspect you'd have to follow the instructions in the README.md file - which would require a clone of the repo.
I never got around to adding it to the pip registry.

**Comment by SiddAjriY2Jaccount** [comment]
Alright, thanks!
